// File generated by FlutterFire CLI / SafeCircle Config.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoWebApiKeySafeCircle123456',
    appId: '1:1234567890:web:safecircle123456',
    messagingSenderId: '1234567890',
    projectId: 'safecircle-app',
    authDomain: 'safecircle-app.firebaseapp.com',
    storageBucket: 'safecircle-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoAndroidApiKeySafeCircle123',
    appId: '1:1234567890:android:safecircle123',
    messagingSenderId: '1234567890',
    projectId: 'safecircle-app',
    storageBucket: 'safecircle-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoIosApiKeySafeCircle12345',
    appId: '1:1234567890:ios:safecircle12345',
    messagingSenderId: '1234567890',
    projectId: 'safecircle-app',
    iosBundleId: 'com.safecircle.safecircle',
  );
}
